# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be7aa7789f66313ae573746afdb8262704ce6ddb745ec879690b22648cd50b1ab539519206e0f6bbab93d87561b82ac200672b8a90391c6f7f005c422112046

test:
  secret_key_base: 23025230269d993fe15b7e6b3936c2dffb16e77089bdcf84919aa7896fa51222272a698920b9d6e8be09742efc8ff96e65d4910365e24a715dede804de85c39e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
